title: ⏰ Conference Deadlines
description: Countdowns to conference deadlines
author: Konstantin Grotov

domain: 'konstantgr.github.io'
baseurl: 'ai-agents-deadlines'

twitter_hashtag: ''
github_username: konstantgr
github_repo: ai-agents-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
